const css = `
.dsh_ref_rail{display:flex;flex-wrap:wrap;gap:6px;width:calc(100% - var(--dsh-composer-side-clearance)*2);max-width:var(--dsh-composer-card-max-width);margin:0 auto}.dsh_ref_chip{display:inline-flex;align-items:center;height:28px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1)}.dsh_ref_open,.dsh_ref_remove{border:0;background:none;color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer}.dsh_ref_open{padding:0 6px 0 10px;max-width:420px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dsh_ref_remove{width:24px;color:var(--dsw-alias-label-dimmed);font-size:18px}.dsh_ref_settings{display:flex;flex-direction:column;gap:12px}.dsh_ref_settings label,.dsh_ref_card{display:flex;flex-direction:column;gap:5px}.dsh_ref_settings input{height:34px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary)}.dsh_ref_card{padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px}.dsh_ref_actions,.dsh_ref_provider_grid{display:flex;flex-wrap:wrap;gap:8px}.dsh_ref_settings button{min-height:32px;padding:0 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);cursor:pointer}
.dsh_ref_toggle{flex-direction:row;align-items:center;gap:8px}.dsh_ref_hint{color:var(--dsw-alias-label-dimmed);font-size:12px}
.dsh_ref_provider_cell{display:flex;flex-direction:column;align-items:flex-start;gap:2px}.dsh_ref_provider_caption{color:var(--dsw-alias-label-dimmed);font-size:11px}
.dsh_ref_progress_wrap{display:flex;flex-direction:column;gap:4px}.dsh_ref_progress_track{height:6px;border-radius:3px;background:var(--dsw-alias-bg-layer-1);border:1px solid var(--dsw-alias-border-l2);overflow:hidden}.dsh_ref_progress_fill{height:100%;background:var(--dsw-alias-label-primary);transition:width .2s ease}.dsh_ref_progress_label{margin:0;color:var(--dsw-alias-label-dimmed);font-size:12px}
.dsh_ref_manage{display:flex;flex-direction:column;gap:10px;padding-top:8px;border-top:1px solid var(--dsw-alias-border-l2)}.dsh_ref_manage h3{margin:0;font-size:14px}.dsh_ref_manage_filters{display:flex;gap:8px}.dsh_ref_manage_filters input{flex:1;height:34px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary)}.dsh_ref_manage_filters select{height:34px;padding:0 8px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary)}.dsh_ref_manage_empty{margin:0;color:var(--dsw-alias-label-dimmed);font-size:13px}
.dsh_ref_manage_list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:6px;max-height:320px;overflow-y:auto}.dsh_ref_manage_row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px}.dsh_ref_manage_title_row{display:flex;align-items:center;gap:6px;flex-wrap:wrap;min-width:0}.dsh_ref_manage_title{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:320px}.dsh_ref_manage_meta{color:var(--dsw-alias-label-dimmed);font-size:12px;white-space:nowrap}
.dsh_ref_badge{padding:1px 8px;border-radius:10px;border:1px solid var(--dsw-alias-border-l2);font-size:11px;color:var(--dsw-alias-label-dimmed)}.dsh_ref_badge_warn{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary)}
.dsh_ref_danger{color:var(--dsw-alias-state-error-primary)}.dsh_ref_danger:hover{background:var(--dsw-alias-interactive-bg-hover-danger)}
.dsh_ref_pagination{display:flex;align-items:center;justify-content:center;gap:12px;font-size:12px;color:var(--dsw-alias-label-dimmed)}
`
export function adoptStyles(): void {
  if (document.getElementById('dsh-reference-anything-style')) return
  const style = document.createElement('style'); style.id = 'dsh-reference-anything-style'; style.textContent = css; document.head.appendChild(style)
}
